<?php /* @var $block \Bigfishpaymentgateway\Pmgw\Block\Success */?>
<?php if ($block->getOrderId() && $block->getCanViewOrder()):?>
    <?php /** @var \stdClass $response */ ?>
    <?php $response = $block->getResponse(); ?>
    <?php $methodTitle = $block->getMethodTitle(); ?>
    <?php $currencyCode = $block->getOrderCurrencyCode(); ?>
    <?php $total = $block->getOrderTotal(); ?>
    <?php $updatedAt = $block->getOrderUpdatedAt(); ?>
    <?php if ($response && is_object($response)): ?>

        <?php if ($updatedAt): ?>
            <p><?php echo __('Transaction date: %1', $updatedAt); ?></p>
        <?php endif; ?>

        <?php if ($currencyCode && $total): ?>
            <p><?php echo __('Amount: %1 %2', $total, $currencyCode); ?></p>
        <?php endif; ?>

        <?php if (property_exists($response, 'ResultCode') && ($response->ResultCode === \BigFish\PaymentGateway::RESULT_CODE_USER_CANCEL || $response->ResultCode === \BigFish\PaymentGateway::RESULT_CODE_TIMEOUT)): ?>
            <p><?php echo __('Cancelled transaction.'); ?></p>
            <p><?php echo __('You have interrupted the payment process or run out of the maximum time limit available!'); ?></p>
        <?php endif; ?>

        <?php if (property_exists($response, 'ResultCode') && $response->ResultCode === \BigFish\PaymentGateway::RESULT_CODE_ERROR): ?>
            <p><?php echo __('Unsuccessful transaction.'); ?></p>
            <p><?php echo __('Please double-check the data you have entered on the payment page. If all the data were correct, please contact your card issuing bank to investigate the cause of rejection.'); ?></p>
        <?php endif; ?>

        <?php if (property_exists($response, 'ResultMessage')): ?>
            <p><?php echo __('Result message: %1', $response->ResultMessage); ?></p>
        <?php endif; ?>

        <?php if (property_exists($response, 'ProviderTransactionId') && !empty($response->ProviderTransactionId)): ?>
            <p><?php echo __('%1 Provider transaction id: %2', $methodTitle, $response->ProviderTransactionId); ?></p>
        <?php endif; ?>

    <?php endif; ?>
<?php endif;?>
