<?php /* @var $block \Bigfishpaymentgateway\Pmgw\Block\Success */?>
<?php if ($block->getOrderId()):?>
    <?php /** @var \stdClass $response */ ?>
    <?php $response = $block->getResponse(); ?>
    <?php $methodTitle = $block->getMethodTitle(); ?>
    <?php $currencyCode = $block->getOrderCurrencyCode(); ?>
    <?php $total = $block->getOrderTotal(); ?>
    <?php $updatedAt = $block->getOrderUpdatedAt(); ?>
    <?php if ($response && is_object($response)): ?>

        <?php if ($updatedAt): ?>
        <p><?php echo __('Transaction date: %1', $updatedAt); ?></p>
        <?php endif; ?>

        <?php if ($currencyCode && $total): ?>
        <p><?php echo __('Amount: %1 %2', $total, $currencyCode); ?></p>
        <?php endif; ?>

        <?php if ($response->ResultCode === \BigFish\PaymentGateway::RESULT_CODE_PENDING || $response->ResultCode === \BigFish\PaymentGateway::RESULT_CODE_OPEN): ?>
            <p><?php echo __('Please be informed that the transaction has started with the following data, processing is in progress. We will notify you by email as soon as the transaction is successful.'); ?></p>
        <?php endif; ?>

        <?php if ($response->ResultCode === \BigFish\PaymentGateway::RESULT_CODE_SUCCESS && $response->ResultMessage): ?>
        <p><?php echo __('Result message: %1', ($response->ProviderName == \BigFish\PaymentGateway::PROVIDER_OTP_SIMPLE ? __('Successful transaction') : $response->ResultMessage)); ?></p>
        <?php endif; ?>

        <?php if ($response->ProviderTransactionId): ?>
            <?php if ($response->ProviderName == \BigFish\PaymentGateway::PROVIDER_CIB): ?>
                <p><?php echo __('Transaction ID (TRID): %1', $response->ProviderTransactionId); ?></p>
            <?php else: ?>
                <p><?php echo __('%1 Provider transaction id: %2', $methodTitle, $response->ProviderTransactionId); ?></p>
            <?php endif; ?>
        <?php endif; ?>

        <?php if ($response->Anum): ?>
        <p><?php echo __('Anum: %1', $response->Anum); ?></p>
        <?php endif; ?>

    <?php endif; ?>
<?php endif;?>
