<?php /* @var $block \Bigfishpaymentgateway\Pmgw\Block\Success */?>
<?php if ($block->getOrderId() && $block->getCanViewOrder()):?>
    <?php /** @var \stdClass $response */ ?>
    <?php $response = $block->getResponse(); ?>
    <?php $methodTitle = $block->getMethodTitle(); ?>
    <?php $currencyCode = $block->getOrderCurrencyCode(); ?>
    <?php $total = $block->getOrderTotal(); ?>
    <?php $updatedAt = $block->getOrderUpdatedAt(); ?>
    <?php if ($response && is_object($response)): ?>
        
        <?php if ($updatedAt): ?>
        <p><?php echo __('Transaction date: %1', $updatedAt); ?></p>
        <?php endif; ?>

        <?php if ($currencyCode && $total): ?>
        <p><?php echo __('Amount: %1 %2', $total, $currencyCode); ?></p>
        <?php endif; ?>

        <?php if (property_exists($response, 'ResultCode') && ($response->ResultCode === \BigFish\PaymentGateway::RESULT_CODE_PENDING || $response->ResultCode === \BigFish\PaymentGateway::RESULT_CODE_OPEN)): ?>
            <p><?php echo __('Please be informed that the transaction has started with the following data, processing is in progress. We will notify you by email as soon as the transaction is successful.'); ?></p>
        <?php endif; ?>

        <?php if (property_exists($response, 'ResultCode') && $response->ResultCode === \BigFish\PaymentGateway::RESULT_CODE_SUCCESS && property_exists($response, 'ResultMessage')): ?>
        <p><?php echo __('Result message: %1', ($response->ProviderName == \BigFish\PaymentGateway::PROVIDER_OTP_SIMPLE ? __('Successful transaction') : $response->ResultMessage)); ?></p>
        <?php endif; ?>

        <?php if (property_exists($response, 'ProviderTransactionId')): ?>
        <p><?php echo __('%1 Provider transaction id: %2', $methodTitle, $response->ProviderTransactionId); ?></p>
        <?php endif; ?>

        <?php if (property_exists($response, 'Anum') && !empty($response->Anum)): ?>
        <p><?php echo __('Anum: %1', $response->Anum); ?></p>
        <?php endif; ?>

    <?php endif; ?>
<?php endif;?>
