<?php /* @var $block \Bigfishpaymentgateway\Pmgw\Block\Success */?>
<?php if ($block->getOrderId() && $block->getCanViewOrder()):?>
    <?php /** @var \stdClass $response */ ?>
    <?php $response = $block->getResponse(); ?>
    <?php if ($response && is_object($response)): ?>
        <?php if (property_exists($response, 'ResultMessage')): ?>
        <p><?php echo __('Result message: %1', $response->ResultMessage); ?></p>
        <?php endif; ?>

        <?php if (property_exists($response, 'ProviderTransactionId')): ?>
        <p><?php echo __('Provider transaction id: %1', $response->ProviderTransactionId); ?></p>
        <?php endif; ?>

        <?php if (property_exists($response, 'Anum')): ?>
        <p><?php echo __('Anum: %1', $response->Anum); ?></p>
        <?php endif; ?>
    <?php endif; ?>
<?php endif;?>
